todoapp:
  image: johscheuer/todo-app-web
  links:
   - redismaster:redis-master
   - redisslave:redis-slave
  ports:
   - "3000:3000"
redisslave:
  image: johscheuer/redis-slave:v1
  links:
   - redismaster
redismaster:
  image: redis
