kind: "ReplicationController"
apiVersion: "v1"
metadata:
  name: "redis-master"
  labels:
    name: "redis-master"
spec:
  replicas: 1
  selector:
    name: "redis-master"
  template:
    metadata:
      labels:
        name: "redis-master"
    spec:
      containers:
        - name: "redis-master"
          image: "redis:3"
          ports:
            - containerPort: 6379
              protocol: "TCP"
